reference_folder = "//media/DISK1/exome_aggregation/GATK_b37"
output_folder = "//media/DISK1/exome_aggregation/exome_test/OUTPUT/"
input_folder = "//media/DISK1/exome_aggregation/fastqs"
bwa_index_HG1K37 = reference_folder+"/human_g1k_v37"
reference_fasta_HG1K37 = reference_folder+"/human_g1k_v37.fasta"
dbsnp_vcf_HG1K37 = "//media/DISK1/exome_aggregation/gatk-bundle-b37/dbsnp_138.b37.vcf.idx.gz"
max_nr_threads= "20"
